begin;

create schema if not exists animals;

create table if not exists animals.animal_type (
	id_type int generated by default as identity primary key,
	type nchar(50),
	is_wild bool
);

create table if not exists animals.creature (
	id_creature bigint generated by default as identity primary key,
	name text,
	type_id int references animals.animal_type(id_type) on delete set null,
	age int2
);

create table if not exists animals.habitat (
	id_area int generated by default as identity primary key,
	area text
);

create table if not exists animals.animals_habitats (
    id_animal_type int references animals.animal_type(id_type) on delete set null on update cascade,
    id_area int references animals.habitat(id_area) on delete cascade on update cascade,

    primary key (id_animal_type, id_area)
);

create table if not exists animals.provider (
	id_provider int generated by default as identity primary key,
	name text,
	phone nchar(50)
);

create table if not exists animals.animals_providers (
	id_animal_type int references animals.animal_type(id_type) on delete set null on update cascade,
	id_provider int references animals.provider(id_provider) on delete cascade on update cascade,

	primary key (id_animal_type, id_provider)
);

end;