create table animals.habitat (
	id_area int generated by default as identity primary key,
	area text,
);

create table animals.animals_habitats (
    id_animal_type int references animals.animal_type(id_type) on delete set null on update cascade,
    id_area int references animals.habitat(id_area) on delete cascade on update cascade
);

create table animals.provider (
	id_provider int generated by default as identity primary key,
	name text,
	phone nchar(50)
);

create table animals.animals_providers (
	id_animal_type int references animals.animal_type(id_type) on delete set null on update cascade,
	id_provider int references animals.provider(id_provider) on delete cascade on update cascade
);