animal:
  names: [Taison, Jessi, Lord, Barsik, Kuzya, Murzik, Jack, Bonya]

application:
  animal:
    log.enabled: true
    log.path: 'create-animal-starter/src/main/resources/animals/logData.txt'
    secret-information.path: 'create-animal-starter/src/main/resources/secretStore/secretInformation.txt'
    directory.result: 'create-animal-starter/src/main/resources/results'
