animal:
  names: [Taison, Jessi, Lord, Barsik, Kuzya, Murzik, Jack, Bonya]
habitat:
  area: [Savannah, Forest, Ocean, Desert, Jungle]
provider:
  name: [Zoo A, Zoo B, Wildlife Sanctuary, Predator Store, Animal Shelter]
  phone: [123-456-7890, 987-654-3210, 555-555-5555, 777-777-7777, 999-999-9999]

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5430/animalsdb'
    username: postgres
    password: postgres
    driver-class-name: 'org.postgresql.Driver'

  sql:
    init:
      schema-locations: 'classpath:db/schema.sql'
      data-locations: 'classpath:db/data.sql'
      mode: never



application:
  animal:
    log.enabled: true
    log.path: 'create-animal-starter/src/main/resources/animals/logData.txt'
    secret-information.path: 'create-animal-starter/src/main/resources/secretStore/secretInformation.txt'
    directory.result: 'create-animal-starter/src/main/resources/results'
