animal:
  names: [Taison, Jessi, Lord, Barsik, Kuzya, Murzik, Jack, Bonya]
habitat:
  area: [Savannah, Forest, Ocean, Desert, Jungle]
provider:
  name: [Zoo A, Zoo B, Wildlife Sanctuary, Predator Store, Animal Shelter]
  phone: [123-456-7890, 987-654-3210, 555-555-5555, 777-777-7777, 999-999-9999]

spring:
  mvc.hiddenmethod.filter.enabled: true
  datasource:
    url: 'jdbc:postgresql://localhost:5430/animalsdb'
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    default-schema: animals
    user: postgres
    password: postgres
    url: 'jdbc:postgresql://localhost:5430/animalsdb'

application:
  animal:
    log.enabled: true
    log.path: 'create-animal-starter/src/main/resources/animals/logData.txt'
    secret-information.path: 'create-animal-starter/src/main/resources/secretStore/secretInformation.txt'
    directory.result: 'create-animal-starter/src/main/resources/results'
